Update cuny_requirement_blocks & update_blocks
Save block diffs in history. Use == instead of hexdigest for compares.

diff --git a/dgw_info/update_requirement_blocks b/dgw_info/update_requirement_blocks
--- a/dgw_info/update_requirement_blocks
+++ b/dgw_info/update_requirement_blocks
@@ -38,7 +38,6 @@
   if [[ $skip_downloads == True ]]
   then echo 'Skipping download step'
   else
-    echo 'Get latest dap_req_block ... '
     # Download new dgw_dap_req_block.csv if Tumbleweed access is possible and there is one from
     # OAREDA.
     if [[ `hostname` =~ cuny.edu ]]
@@ -49,37 +48,40 @@
           then echo "Download failed!" 1>&2
           else echo '... done.'
           fi
-    else echo "Unable to access Tumbleweed from `hostname`"
+    else echo "Unable to access Tumbleweed from `hostname`" 1>&2
+         exit 1
     fi
   fi
 
-    # Sanity check on file size. Should be within 10% of latest ... if there is a download
-    if [[ -e $current_download_file && ! $ignore_size ]]
-    then
-      size_download=`/usr/local/opt/coreutils/libexec/gnubin/stat -c %s $current_download_file`
-      size_latest=`/usr/local/opt/coreutils/libexec/gnubin/stat -c %s $latest_archive_file`
-      if [[ `echo "define abs(x) {if (x < 0) return (-x) else return (x)}; scale=6; \
-                  (abs(($size_download - $size_latest) / $size_latest) > 0.1)" | bc` != 0 ]]
-      then
-           echo Notice from `hostname` > msg
-           printf "Downloaded size (%'d bytes) is over 10% different \n" $size_download >> msg
-           printf "from latest archive size (%'d bytes).\n" $size_latest >> msg
-           /Users/vickery/bin/sendemail -s "dgw_dap_req_block.csv download failed" \
-           -t msg cvickery@qc.cuny.edu
-           rm msg
-
-        printf "Downloaded size (%'d bytes) is over 10% different \n" $size_download 1>&2
-        printf "from latest archive size (%'d bytes).\n" $size_latest 1>&2
-        ls -lh $latest_archive_file ./downloads
-        if [[ -e $current_download_file ]]
-        then
-            rm -f $current_download_file
-            echo "Removed lousy download"
-        fi
-        exit 1
-      fi
+    if [[ $ignore_size ]]
+    then echo 'Skipping size check'
     else
-      echo "Skipping size check"
+      # Sanity check on file size. Should be within 10% of latest ... if there is a download
+      if [[ -e $current_download_file ]]
+      then
+        size_download=`/usr/local/opt/coreutils/libexec/gnubin/stat -c %s $current_download_file`
+        size_latest=`/usr/local/opt/coreutils/libexec/gnubin/stat -c %s $latest_archive_file`
+        if [[ `echo "define abs(x) {if (x < 0) return (-x) else return (x)}; scale=6; \
+                    (abs(($size_download - $size_latest) / $size_latest) > 0.1)" | bc` != 0 ]]
+        then
+             echo Notice from `hostname` > msg
+             printf "Downloaded size (%'d bytes) is over 10% different \n" $size_download >> msg
+             printf "from latest archive size (%'d bytes).\n" $size_latest >> msg
+             /Users/vickery/bin/sendemail -s "dgw_dap_req_block.csv download failed" \
+             -t msg cvickery@qc.cuny.edu
+             rm msg
+
+          printf "Downloaded size (%'d bytes) is over 10% different \n" $size_download 1>&2
+          printf "from latest archive size (%'d bytes).\n" $size_latest 1>&2
+          ls -lh $latest_archive_file ./downloads
+          if [[ -e $current_download_file ]]
+          then
+              rm -f $current_download_file
+              echo "Removed lousy download"
+          fi
+          exit 1
+        fi
+      fi
     fi
 
   # # Pick the csv file to work with: either the newly-downloaded one or the most-recent archived one.
